version: '3'

services:
  web:
    build: .
    image: stepik-django
    ports:
    - 8000:8000
    volumes:
    - .:/home/box
    environment:
      DJANGO_SETTINGS_MODULE: ask.dev_settings
    depends_on:
    - db

  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: 111111
      MYSQL_DATABASE: qa
      MYSQL_USER: root
    volumes:
      - db:/var/lib/mysql

  db_client:
    image: mysql:5.6
    environment:
      MYSQL_PWD: 111111
      MYSQL_HOST: db
    entrypoint: mysql
    depends_on:
      - db

volumes:
  db:
