version: '3.4'

services:
  nginx:
    image: nginx:1.13.6
    volumes:
    - ./public:/home/box/web/public
    - ./etc/nginx-docker.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 80:80
    depends_on:
    - backend

  backend:
    build: .
    image: stepik-django
    ports:
    - 8000:8000
    volumes:
    - .:/home/box/web
    environment:
      DJANGO_SETTINGS_MODULE: ask.dev_settings
    depends_on:
    - db

  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: 111111
      MYSQL_DATABASE: qa
      MYSQL_USER: root
    volumes:
      - db:/var/lib/mysql

  db_client:
    image: mysql:5.6
    environment:
      MYSQL_PWD: 111111
      MYSQL_HOST: db
    entrypoint: mysql
    depends_on:
      - db

volumes:
  db:
